<div id="jbn{dede:global name=itemindex runphp='yes'}@me=@me;{/dede:global}" style="display:{dede:global.itemindex  runphp='yes'}if(@me==1){@me='block';}else{@me='none';}{/dede:global.itemindex}">
          <div class="jbnnt"> 
          {dede:channel type='son' row='8'} 
<a id="jbb[field:autoindex runphp='yes']@me=$GLOBALS['autoindex']+0;[/field:autoindex]" href='[field:typelink/]'  class="[field:global name='autoindex' runphp='yes']if(@me==1){@me="on";}else{@me='';}[/field:global]">[field:typename/]</a>
{/dede:channel} 
          </div>
          <div class="jbnnn">
            <div id="jbbn1" style="display:block;">
              <div class="tuijians mt10">
                <div class="tuijiansl fl">
                  <dl>
                    <dt><a href="/zc/zc/822.html" target="_blank" title="瞄准痔疮的症状——针"><img src="/images/1529201144-0-lp.jpg" alt="瞄准痔疮的症状——针" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/zc/822.html" target="_blank">瞄准痔疮的症状——针</a></span>
                      <p>很多人都会出现便秘、便血、脱出等症状，北京某某肛肠医院的专家表示：这些都是痔疮的常见症状，很多人出现这<a href="/zc/zc/822.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/zc/" target="_blank">痔疮</a>]</span><a href="/zc/zc/826.html" target="_blank" title="痔疮的手术治疗费用多少钱？怎么治疗好">痔疮的手术治疗费用多少钱？怎么治疗好</a></li>
                    <li>·<span>[<a href="/zc/zc/" target="_blank">痔疮</a>]</span><a href="/zc/zc/831.html" target="_blank" title="痔疮的原因是什么？是怎样形成的？">痔疮的原因是什么？是怎样形成的？</a></li>
                    <li>·<span>[<a href="/zc/zc/" target="_blank">痔疮</a>]</span><a href="/zc/zc/519.html" target="_blank" title="北京治痔疮哪个医院好">北京治痔疮哪个医院好</a></li>
                  </ul>
                </div>
                <div class="tuijiansl fr">
                  <dl>
                    <dt><a href="/zc/zc/879.html" target="_blank" title="产后痔疮百科？"><img src="/images/16035mu6-0-lp.jpg" alt="产后痔疮百科？" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/zc/879.html" target="_blank">产后痔疮百科？</a></span>
                      <p>导读： 想知道产后得了痔疮怎么办? 首先要了解产妇产生痔疮的原因。痔疮主要是因为怀孕期间我们子宫大，压迫下<a href="/zc/zc/879.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/zc/" target="_blank">痔疮</a>]</span><a href="/zc/zc/879.html" target="_blank" title="产后痔疮百科？">产后痔疮百科？</a></li>
                    <li>·<span>[<a href="/zc/zc/" target="_blank">痔疮</a>]</span><a href="/zc/zc/878.html" target="_blank" title="PPH如何治疗痔疮？手术费用多少钱？">PPH如何治疗痔疮？手术费用多少钱？</a></li>
                    <li>·<span>[<a href="/zc/zc/" target="_blank">痔疮</a>]</span><a href="/zc/zc/559.html" target="_blank" title="北京最好的痔疮肛肠医院">北京最好的痔疮肛肠医院</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div id="jbbn2" style="display:none;">
              <div class="tuijians mt10">
                <div class="tuijiansl fl">
                  <dl>
                    <dt><a href="/zc/nz/872.html" target="_blank" title="如何区分内痔和外痔？"><img src="/images/1411314q7-0-lp.png" alt="如何区分内痔和外痔？" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/nz/872.html" target="_blank">如何区分内痔和外痔？</a></span>
                      <p>痔疮可以分为内痔、外痔和混合痔。这三中痔疮的临床表现也各自不同。内痔和外痔的区别在于一个在肛门外，一个<a href="/zc/nz/872.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/nz/" target="_blank">内痔</a>]</span><a href="/zc/nz/874.html" target="_blank" title="内痔不担心--三大特色微创技术一招搞定">内痔不担心--三大特色微创技术一招搞定</a></li>
                    <li>·<span>[<a href="/zc/nz/" target="_blank">内痔</a>]</span><a href="/zc/nz/873.html" target="_blank" title="内痔出血怎么办？">内痔出血怎么办？</a></li>
                    <li>·<span>[<a href="/zc/nz/" target="_blank">内痔</a>]</span><a href="/zc/nz/618.html" target="_blank" title="内痔脱出的症状?怎么治疗?">内痔脱出的症状?怎么治疗?</a></li>
                  </ul>
                </div>
                <div class="tuijiansl fr">
                  <dl>
                    <dt><a href="/zc/nz/648.html" target="_blank" title="肛门内痔是什么?内痔是"><img src="/images/11293432g-0-lp.jpg" alt="肛门内痔是什么?内痔是" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/nz/648.html" target="_blank">肛门内痔是什么?内痔是</a></span>
                      <p>内痔生于齿线以上和肛门3cm处，称为内痔。《外科大成痔疮》中说：内痔在肛门之里，大便则出血如箭，解毕用手按<a href="/zc/nz/648.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/nz/" target="_blank">内痔</a>]</span><a href="/zc/nz/859.html" target="_blank" title="内痔是怎么回事？怎么治疗？">内痔是怎么回事？怎么治疗？</a></li>
                    <li>·<span>[<a href="/zc/nz/" target="_blank">内痔</a>]</span><a href="/zc/nz/633.html" target="_blank" title="内痔百科-内痔怎么办？">内痔百科-内痔怎么办？</a></li>
                    <li>·<span>[<a href="/zc/nz/" target="_blank">内痔</a>]</span><a href="/zc/nz/643.html" target="_blank" title="内痔脱出图片—内痔脱出的原因、症状、">内痔脱出图片—内痔脱出的原因、症状、</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div id="jbbn3" style="display:none;">
              <div class="tuijians mt10">
                <div class="tuijiansl fl">
                  <dl>
                    <dt><a href="/zc/wz/863.html" target="_blank" title="患了外痔怎么办？如何"><img src="/images/4-150q0105q9163-lp.jpg" alt="患了外痔怎么办？如何" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/wz/863.html" target="_blank">患了外痔怎么办？如何</a></span>
                      <p>患了外痔怎么办？?外痔的治疗方法，北京某某肛肠医院肛肠科主任指出：外痔位于齿线以下，是由痔外静脉丛曲张或<a href="/zc/wz/863.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/wz/" target="_blank">外痔</a>]</span><a href="/zc/wz/863.html" target="_blank" title="患了外痔怎么办？如何治疗？">患了外痔怎么办？如何治疗？</a></li>
                    <li>·<span>[<a href="/zc/wz/" target="_blank">外痔</a>]</span><a href="/zc/wz/651.html" target="_blank" title="图说外痔怎么回事?">图说外痔怎么回事?</a></li>
                    <li>·<span>[<a href="/zc/wz/" target="_blank">外痔</a>]</span><a href="/zc/wz/662.html" target="_blank" title="外痔如何检查诊断?外痔诊疗">外痔如何检查诊断?外痔诊疗</a></li>
                  </ul>
                </div>
                <div class="tuijiansl fr">
                  <dl>
                    <dt><a href="/zc/wz/665.html" target="_blank" title="治疗外痔医院哪家好"><img src="/images/15140561w-0-lp.jpg" alt="治疗外痔医院哪家好" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/wz/665.html" target="_blank">治疗外痔医院哪家好</a></span>
                      <p>近几年来，随着社会水平的提高，人们身体发病率也是越来越高，而痔疮是属于高发病的一种。外痔长在肛门外部周<a href="/zc/wz/665.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                  </ul>
                </div>
              </div>
            </div>
            <div id="jbbn4" style="display:none;">
              <div class="tuijians mt10">
                <div class="tuijiansl fl">
                  <dl>
                    <dt><a href="/zc/hhz/694.html" target="_blank" title="北京治疗混合痔疮哪家"><img src="/images/2-1504261h355w3-lp.jpg" alt="北京治疗混合痔疮哪家" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/hhz/694.html" target="_blank">北京治疗混合痔疮哪家</a></span>
                      <p>北京某某肛肠医院 北京肛肠疾病专科医院 北京某某肛肠医院拥有众多特色权威技术，如痔动脉结扎技术、PPH微创技术<a href="/zc/hhz/694.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/hhz/" target="_blank">混合痔</a>]</span><a href="/zc/hhz/776.html" target="_blank" title="肛门混合痔症状表现是什么？">肛门混合痔症状表现是什么？</a></li>
                    <li>·<span>[<a href="/zc/hhz/" target="_blank">混合痔</a>]</span><a href="/zc/hhz/680.html" target="_blank" title="混合痔百科">混合痔百科</a></li>
                    <li>·<span>[<a href="/zc/hhz/" target="_blank">混合痔</a>]</span><a href="/zc/hhz/678.html" target="_blank" title="混合痔有哪些注意事项?混合痔如何防治">混合痔有哪些注意事项?混合痔如何防治</a></li>
                  </ul>
                </div>
                <div class="tuijiansl fr">
                  <dl>
                    <dt><a href="/zc/hhz/692.html" target="_blank" title="混合痔的治疗费用需要"><img src="/images/1h0535554-0-lp.jpg" alt="混合痔的治疗费用需要" width="150" height="150" /></a></dt>
                    <dd> <span><a href="/zc/hhz/692.html" target="_blank">混合痔的治疗费用需要</a></span>
                      <p>好疗法，省钱：PP微创术彻底治愈混合痔不复发 强生微创痔疮手术(PPH)又称为痔上黏膜环切术，是建立在肛垫学说基础<a href="/zc/hhz/692.html" target="_blank">[详细]</a></p>
                    </dd>
                  </dl>
                  <div class="clear"></div>
                  <ul>
                    <li>·<span>[<a href="/zc/hhz/" target="_blank">混合痔</a>]</span><a href="/zc/hhz/692.html" target="_blank" title="混合痔的治疗费用需要多少钱?">混合痔的治疗费用需要多少钱?</a></li>
                    <li>·<span>[<a href="/zc/hhz/" target="_blank">混合痔</a>]</span><a href="/zc/hhz/691.html" target="_blank" title="某某专家详解——混合痔四大病因">某某专家详解——混合痔四大病因</a></li>
                    <li>·<span>[<a href="/zc/hhz/" target="_blank">混合痔</a>]</span><a href="/zc/hhz/689.html" target="_blank" title="混合痔图片——混合痔特征及症状">混合痔图片——混合痔特征及症状</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>