<?php
$z[0]=Array("global","@me=@me;",12,75);
$z[0][4]=array();
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","if(@me==1){@me='block';}else{@me='none';}",92,194);
$z[1][4]=array();
$z[1][4]['name']="itemindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel"," \r\n<a id=\"jbb[field:autoindex runphp='yes']@me=\$GLOBALS['autoindex']+0;[/field:autoindex]\" href='[field:typelink/]'  class=\"[field:global name='autoindex' runphp='yes']if(@me==1){@me=\"on\";}else{@me='';}[/field:global]\">[field:typename/]</a>\r\n",240,530);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['row']="8";

?>