<?php
$z[0]=Array("arcurl","",67,82);
$z[0][4]=array();
$z[1]=Array("title","",94,108);
$z[1][4]=array();
$z[2]=Array("description","",262,312);
$z[2][4]=array();
$z[2][4]['function']="cn_substr(@me,320)";
$z[3]=Array("arcurl","",324,339);
$z[3][4]=array();
$z[4]=Array("click","",398,412);
$z[4][4]=array();
$z[5]=Array("pubdate","",423,469);
$z[5][4]=array();
$z[5][4]['function']="GetDateTimeMK(@me)";

?>