<a id="jb{dede:global name=itemindex runphp='yes'}@me=@me;{/dede:global}" class="{dede:global.itemindex  runphp='yes'}if(@me==1){@me='on';}else{@me='';}{/dede:global.itemindex}">
          <li> <span></span>
            <h3>{dede:field name='typename'/}诊疗专区<i>
            <script>if({dede:field.typeid/} == 8){
           document.write("Hemorrhoids disease");
        }
		if({dede:field.typeid/} == 9){
           document.write("The anus injury");
        }
		if({dede:field.typeid/} == 10){
           document.write("Crissum diseases");
        }
		if({dede:field.typeid/} == 11){
           document.write("The discharge of disease");
        }
		if({dede:field.typeid/} == 12){
           document.write("Intestinal disease");
        }

</script></i></h3>
          </li>
          </a>