<?php
$z[0]=Array("arcurl","",67,82);
$z[0][4]=array();
$z[1]=Array("title","",94,108);
$z[1][4]=array();
$z[2]=Array("description","",262,311);
$z[2][4]=array();
$z[2][4]['function']="cn_substr(@me,80)";
$z[3]=Array("arcurl","",323,338);
$z[3][4]=array();
$z[4]=Array("click","",397,411);
$z[4][4]=array();
$z[5]=Array("pubdate","",422,468);
$z[5][4]=array();
$z[5][4]['function']="GetDateTimeMK(@me)";

?>