<?php
$z[0]=Array("global","@me=@me;",14,77);
$z[0][4]=array();
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","if(@me==1){@me='block';}else{@me='none';}",94,196);
$z[1][4]=array();
$z[1][4]['name']="itemindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("arclist","\r\n                    <dt><a href=\"[field:arcurl/]\">[field:image/]</a></dt>\r\n                    <dd> <span><a href=\"[field:arcurl/]\">[field:title/]</a></span>\r\n                      <p>[field:info/]...<a href=\"[field:arcurl/]\">[查看全文]</a></p>\r\n                    </dd>\r\n                  ",330,743);
$z[2][4]=array();
$z[2][4]['limit']="0,1";
$z[2][4]['type']="image.";
$z[2][4]['titlelen']="26";
$z[2][4]['infolen']="80";
$z[3]=Array("arclist","\r\n                    <li>·<a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                  ",857,1011);
$z[3][4]=array();
$z[3][4]['limit']="0,3";
$z[3][4]['titlelen']="50";
$z[4]=Array("arclist","\r\n                    <dt><a href=\"[field:arcurl/]\">[field:image/]</a></dt>\r\n                    <dd> <span><a href=\"[field:arcurl/]\">[field:title/]</a></span>\r\n                      <p>[field:info/]...<a href=\"[field:arcurl/]\">[查看全文]</a></p>\r\n                    </dd>\r\n                  ",1148,1561);
$z[4][4]=array();
$z[4][4]['limit']="1,1";
$z[4][4]['type']="image.";
$z[4][4]['titlelen']="26";
$z[4][4]['infolen']="80";
$z[5]=Array("arclist","\r\n                    <li>·<a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                  ",1675,1829);
$z[5][4]=array();
$z[5][4]['limit']="3,3";
$z[5][4]['titlelen']="50";

?>