<li>
            <dl>
              <a href="[field:arcurl/]">[field:image/]</a></a>
              <p class="p1"></p>
              <p class="p2"><a href="/swt" target="_blank" class="a1">我要咨询</a><a href="/swt" target="_blank">我要预约</a></p>
            </dl>
            <p class="p3"><b>擅长：</b>[field:info function="cn_substr(@me,80)"/]... <a href="[field:arcurl/]" target="_blank">[详情]</a></p>
            <p class="p4"><a href="/swt" target="_blank" class="aa1"><img src="/images/lis_ic01.gif" alt="" /><span>预约量<br />
              <b>[field:click/]</b></span></a> <a href="/swt" target="_blank" class="aa2"><img src="/images/lis_ic01-03.gif" alt="" /><span>疗效满意<br />
              <b>98%</b></span></a></p>
            <div class="null"></div>
          </li>