<dl class="li_box">
            <div>
              <h2><a href="[field:arcurl/]" class="l">[field:title/]</a><a href="/swt" target="_blank" class="R">我要咨询</a></h2>
            </div>
            <div class="null"></div>
            <div class="p1">[field:description function='cn_substr(@me,80)'/]...<a href="[field:arcurl/]">[详情]</a></div>
            <div class="p2">点击：[field:click/]次  发表[field:pubdate function="GetDateTimeMK(@me)"/]</div>
          </dl>