<?php
$z[0]=Array("channelartlist","\r\n        <li>\r\n          <h2><img src=\"/images/id{dede:field.typeid/}.png\" alt=\"痔疮疾病\" /><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></h2>\r\n          <p>\r\n          {dede:channel type='son' row='8'} \r\n<a href='[field:typelink/]'>[field:typename/]</a>\r\n{/dede:channel}</p>\r\n        </li>\r\n      ",969,1369);
$z[0][4]=array();
$z[0][4]['row']="6";
$z[0][4]['typeid']="8,9,10,11";
$z[1]=Array("channel"," \r\n      <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n",1490,1607);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="6";

?>