<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\"></a>",1100,1169);
$z[0][4]=array();
$z[0][4]['typeid']="5";
$z[1]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",1398,1534);
$z[1][4]=array();
$z[1][4]['limit']="0,9";
$z[1][4]['typeid']="7";
$z[1][4]['titlelen']="40";
$z[2]=Array("arclist"," \r\n          <li>\r\n            <dl>\r\n              <a href=\"[field:arcurl/]\">[field:image/]</a></a>\r\n              <p class=\"p1\"></p>\r\n              <p class=\"p2\"><a href=\"/swt\" target=\"_blank\" class=\"a1\">我要咨询</a><a href=\"/swt\" target=\"_blank\">我要预约</a></p>\r\n            </dl>\r\n            <p class=\"p3\"><b>擅长：</b>[field:info function=\"cn_substr(@me,80)\"/]... <a href=\"[field:arcurl/]\" target=\"_blank\">[详情]</a></p>\r\n            <p class=\"p4\"><a href=\"/swt\" target=\"_blank\" class=\"aa1\"><img src=\"/images/lis_ic01.gif\" alt=\"\" /><span>预约量<br />\r\n              <b>[field:click/]</b></span></a> <a href=\"/swt\" target=\"_blank\" class=\"aa2\"><img src=\"/images/lis_ic01-03.gif\" alt=\"\" /><span>疗效满意<br />\r\n              <b>98%</b></span></a></p>\r\n            <div class=\"null\"></div>\r\n          </li>\r\n        ",1648,2589);
$z[2][4]=array();
$z[2][4]['limit']="0,7";
$z[2][4]['type']="image.";
$z[2][4]['typeid']="5";
$z[2][4]['imgwidth']="258";
$z[2][4]['imgheight']="224";

?>